Repository Geik-xyz/Farmer-v6, pull requests merged in 2023-05, with the labels that each got.

#15 Added FabledSkyblock compatibility
  README.md
  pom.xml
  src/main/java/xyz/geik/farmer/integrations/Integrations.java
  src/main/java/xyz/geik/farmer/integrations/fabledskyblock/FabledListener.java
  src/main/java/xyz/geik/farmer/integrations/fabledskyblock/FabledSkyblock.java
  src/main/resources/plugin.yml
Labels: enhancement, good first issue, update

#16 bugfix and enhance
  src/main/java/xyz/geik/farmer/api/managers/FarmerManager.java
  src/main/java/xyz/geik/farmer/commands/Commands.java
  src/main/java/xyz/geik/farmer/database/DBQueries.java
  src/main/java/xyz/geik/farmer/guis/MainGui.java
  src/main/java/xyz/geik/farmer/listeners/backend/ChatEvent.java
  src/main/java/xyz/geik/farmer/model/Farmer.java
  src/main/java/xyz/geik/farmer/modules/autoharvest/AutoHarvestEvent.java
  src/main/java/xyz/geik/farmer/modules/production/Production.java
  src/main/java/xyz/geik/farmer/modules/spawnerkiller/SpawnerKillerEvent.java
  src/main/java/xyz/geik/farmer/modules/voucher/VoucherEvent.java
Labels: bug, enhancement, update

#17 update v6 development branch
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  pom.xml
  src/main/java/xyz/geik/farmer/integrations/Integrations.java
  src/main/java/xyz/geik/farmer/integrations/fabledskyblock/FabledListener.java
  src/main/java/xyz/geik/farmer/integrations/fabledskyblock/FabledSkyblock.java
  src/main/resources/plugin.yml
Labels: documentation, update
