Repository Geik-xyz/Farmer-v6, pull requests merged in 2023-07, with the labels that each got.

#20 Fixes for Farmer duplication
  src/main/java/xyz/geik/farmer/api/managers/FarmerManager.java
  src/main/java/xyz/geik/farmer/database/DBQueries.java
  src/main/java/xyz/geik/farmer/listeners/ListenerRegister.java
  src/main/java/xyz/geik/farmer/listeners/backend/BuyFarmerEvent.java
  src/main/java/xyz/geik/farmer/model/Farmer.java
  src/main/resources/plugin.yml
Labels: bug, fixed issues

#21 end of beta development merge
  src/main/java/xyz/geik/farmer/Main.java
  src/main/java/xyz/geik/farmer/api/managers/FarmerManager.java
  src/main/java/xyz/geik/farmer/database/DBQueries.java
  src/main/java/xyz/geik/farmer/integrations/askyblock/ASkyblockListener.java
  src/main/java/xyz/geik/farmer/integrations/bentobox/BentoListener.java
  src/main/java/xyz/geik/farmer/integrations/fabledskyblock/FabledSkyListener.java
  src/main/java/xyz/geik/farmer/integrations/superior/SuperiorListener.java
  src/main/java/xyz/geik/farmer/listeners/ListenerRegister.java
  src/main/java/xyz/geik/farmer/listeners/backend/BuyFarmerEvent.java
  src/main/java/xyz/geik/farmer/model/Farmer.java
  src/main/java/xyz/geik/farmer/modules/autoseller/AutoSellerEvent.java
  src/main/resources/plugin.yml
Labels: update

#22 Add MySQL Support
  pom.xml
  src/main/java/xyz/geik/farmer/Main.java
  src/main/java/xyz/geik/farmer/api/managers/DatabaseManager.java
  src/main/java/xyz/geik/farmer/api/managers/FarmerManager.java
  src/main/java/xyz/geik/farmer/commands/Commands.java
  src/main/java/xyz/geik/farmer/database/DBConnection.java
  src/main/java/xyz/geik/farmer/database/DBQueries.java
  src/main/java/xyz/geik/farmer/database/DatabaseType.java
  src/main/java/xyz/geik/farmer/database/HikariCP.java
  src/main/java/xyz/geik/farmer/database/MySQL.java
  src/main/java/xyz/geik/farmer/database/SQL.java
  src/main/java/xyz/geik/farmer/database/SQLite.java
  src/main/java/xyz/geik/farmer/integrations/askyblock/ASkyblockListener.java
  src/main/java/xyz/geik/farmer/listeners/backend/QuitEvent.java
  src/main/java/xyz/geik/farmer/model/Farmer.java
  src/main/java/xyz/geik/farmer/model/user/User.java
  src/main/resources/storage/database.yml
Labels: enhancement, good first issue, update

#23 add hexcolor support for 1.16+
  src/main/java/xyz/geik/farmer/Main.java
Labels: enhancement
