Repository Geik-xyz/Farmer-v6, pull requests merged in 2024-06, with the labels that each got.

#52 Improved BentoBox support
  pom.xml
  src/main/java/xyz/geik/farmer/database/MySQL.java
  src/main/java/xyz/geik/farmer/database/SQLite.java
  src/main/java/xyz/geik/farmer/integrations/bentobox/Bento.java
  src/main/java/xyz/geik/farmer/integrations/bentobox/BentoListener.java
Labels: enhancement, good first issue, code cleanup

#56 Land integration fix
  pom.xml
  src/main/java/xyz/geik/farmer/integrations/lands/Lands.java
  src/main/resources/plugin.yml
Labels: enhancement, update, fixed issues

#59 1.21 update
  pom.xml
  src/main/java/xyz/geik/farmer/helpers/gui/GuiHelper.java
  src/main/java/xyz/geik/farmer/modules/spawnerkiller/handlers/SpawnerKillerEvent.java
  src/main/java/xyz/geik/farmer/modules/voucher/helper/VoucherItem.java
  src/main/resources/plugin.yml
Labels: update
