Repository Geik-xyz/Farmer-v6, pull requests merged in 2024-07, with the labels that each got.

#65 Land integration fixes in listener
  src/main/java/xyz/geik/farmer/guis/MainGui.java
  src/main/java/xyz/geik/farmer/integrations/lands/LandsListener.java
Labels: update, fixed issues

#66 Fix GriefPrevention not found & Add FarmerInv#sumItemAmount(XMaterial, int)
  pom.xml
  src/main/java/xyz/geik/farmer/model/inventory/FarmerInv.java
Labels: fixed issues, code cleanup

#69 Fixed perm check on farmer command
  src/main/java/xyz/geik/farmer/commands/FarmerCommand.java
  src/main/java/xyz/geik/farmer/configuration/ConfigFile.java
  src/main/java/xyz/geik/farmer/helpers/WorldHelper.java
  src/main/java/xyz/geik/farmer/listeners/backend/ItemEvent.java
  src/main/java/xyz/geik/farmer/listeners/backend/QuitEvent.java
  src/main/java/xyz/geik/farmer/modules/autoharvest/handlers/AutoHarvestEvent.java
  src/main/java/xyz/geik/farmer/modules/voucher/handlers/VoucherEvent.java
Labels: documentation, enhancement, update, code cleanup
