Repository Geik-xyz/Farmer-v6, pull requests merged in 2024-08, with the labels that each got.

#75 Fix NPE & update some dependencies
  pom.xml
  src/main/java/xyz/geik/farmer/integrations/townyadvanced/TownyListener.java
Labels: update

#77 Added IridiumSkyblock & UltimateClaims support
  README.md
  pom.xml
  src/main/java/xyz/geik/farmer/configuration/ConfigFile.java
  src/main/java/xyz/geik/farmer/integrations/Integrations.java
  src/main/java/xyz/geik/farmer/integrations/iridiumskyblock/IridiumListener.java
  src/main/java/xyz/geik/farmer/integrations/iridiumskyblock/IridiumSkyblock.java
  src/main/java/xyz/geik/farmer/integrations/ultimateclaims/UltimateClaims.java
  src/main/java/xyz/geik/farmer/integrations/ultimateclaims/UltimateListener.java
  src/main/resources/plugin.yml
Labels: documentation, enhancement, help wanted

#74 Unregister commands onDisable
  src/main/java/xyz/geik/farmer/Main.java
  src/main/java/xyz/geik/farmer/helpers/CommandHelper.java
Labels: help wanted, fixed issues

#91 created Rclaim integration
  pom.xml
  src/main/java/xyz/geik/farmer/integrations/Integrations.java
  src/main/java/xyz/geik/farmer/integrations/rclaim/RClaim.java
  src/main/java/xyz/geik/farmer/integrations/rclaim/RClaimListener.java
  src/main/resources/plugin.yml
Labels: enhancement

#93 changed geyser module type
  src/main/java/xyz/geik/farmer/api/handlers/FarmerItemSellEvent.java
  src/main/java/xyz/geik/farmer/api/handlers/FarmerPreLoadItemEvent.java
  src/main/java/xyz/geik/farmer/configuration/ModulesFile.java
  src/main/java/xyz/geik/farmer/guis/MainGui.java
  src/main/java/xyz/geik/farmer/helpers/CacheLoader.java
  src/main/java/xyz/geik/farmer/modules/geyser/Geyser.java
  src/main/java/xyz/geik/farmer/modules/geyser/commands/GeyserCommand.java
  src/main/resources/modules/geyser/lang/en.yml
  src/main/resources/modules/geyser/lang/tr.yml
Labels: update, fixed issues
