Repository Geik-xyz/Farmer-v6, pull requests merged in 2025-02, with the labels that each got.

#117 Updated GLib
  pom.xml
Labels: update

#124 Fixed the problem of adding to UserGUI Fixed server crash issue
  src/main/java/xyz/geik/farmer/guis/UsersGui.java
  src/main/java/xyz/geik/farmer/listeners/ListenerRegister.java
  src/main/java/xyz/geik/farmer/listeners/backend/ChatEvent.java
  src/main/java/xyz/geik/farmer/listeners/backend/FastPlayerLookup.java
Labels: update, fixed issues, code cleanup

#125 b109 merge request
  pom.xml
  src/main/java/xyz/geik/farmer/Main.java
  src/main/java/xyz/geik/farmer/Metrics.java
  src/main/java/xyz/geik/farmer/api/handlers/FarmerBoughtEvent.java
  src/main/java/xyz/geik/farmer/api/handlers/FarmerRemoveEvent.java
  src/main/java/xyz/geik/farmer/api/managers/FarmerManager.java
  src/main/java/xyz/geik/farmer/commands/FarmerCommand.java
  src/main/java/xyz/geik/farmer/configuration/ConfigFile.java
  src/main/java/xyz/geik/farmer/configuration/LangFile.java
  src/main/java/xyz/geik/farmer/configuration/ModulesFile.java
  src/main/java/xyz/geik/farmer/configuration/lang/en.java
  src/main/java/xyz/geik/farmer/configuration/lang/tr.java
  src/main/java/xyz/geik/farmer/database/SQL.java
  src/main/java/xyz/geik/farmer/guis/MainGui.java
  src/main/java/xyz/geik/farmer/guis/UsersGui.java
  src/main/java/xyz/geik/farmer/helpers/ModuleHelper.java
  src/main/java/xyz/geik/farmer/helpers/gui/GroupItems.java
  src/main/java/xyz/geik/farmer/helpers/gui/GuiHelper.java
  src/main/java/xyz/geik/farmer/integrations/Integrations.java
  src/main/java/xyz/geik/farmer/integrations/askyblock/ASkyblockListener.java
  src/main/java/xyz/geik/farmer/integrations/bentobox/BentoListener.java
  src/main/java/xyz/geik/farmer/integrations/fabledskyblock/FabledSkyListener.java
  src/main/java/xyz/geik/farmer/integrations/grief/GriefListener.java
  src/main/java/xyz/geik/farmer/integrations/iridiumskyblock/IridiumListener.java
  src/main/java/xyz/geik/farmer/integrations/lands/Lands.java
  src/main/java/xyz/geik/farmer/integrations/lands/LandsListener.java
  src/main/java/xyz/geik/farmer/integrations/rclaim/RClaimListener.java
  src/main/java/xyz/geik/farmer/integrations/superior/SuperiorListener.java
  src/main/java/xyz/geik/farmer/integrations/townyadvanced/TownyListener.java
  src/main/java/xyz/geik/farmer/integrations/ultimateclaims/UltimateListener.java
  src/main/java/xyz/geik/farmer/listeners/ListenerRegister.java
  src/main/java/xyz/geik/farmer/listeners/backend/BuyFarmerEvent.java
  src/main/java/xyz/geik/farmer/listeners/backend/ChatEvent.java
  src/main/java/xyz/geik/farmer/listeners/backend/FastPlayerLookup.java
  src/main/java/xyz/geik/farmer/listeners/backend/QuitEvent.java
  src/main/java/xyz/geik/farmer/model/Farmer.java
  src/main/java/xyz/geik/farmer/modules/production/handlers/ProductionCalculateEvent.java
  src/main/java/xyz/geik/farmer/modules/production/model/ProductionModel.java
  src/main/resources/plugin.yml
Labels: enhancement, update, big update
